"""Complex test instances for the fully-implemented shading rules.

Each entry provides:
  * ``inst`` — the instance JSON (as accepted by the puzzle server / runner),
  * ``grid`` — a *valid* expected solution (list of rows, '#' = black).  Every
               grid here was generated by the solver and then independently
               validated against ``test/ref.py`` (a pure-Python reading of the
               rule text that shares no code with the DSL), so it is guaranteed
               to satisfy the rule, not just the DSL.
  * ``ref``  — the reference checker to use,
  * ``note`` — short description of what makes this instance a stress test.

The instances are deliberately larger / denser / more constrained than the
samples in ``impls/samples/``.
"""

from . import ref


def G(text):
    """Parse a picture into a {(r, c): 0|1} board."""
    board = {}
    for r, line in enumerate(text.strip().splitlines()):
        for c, ch in enumerate(line.split()):
            board[(r, c)] = 1 if ch == "#" else 0
    return board


def _block_regions(rows, cols, h=2, w=2):
    per = (cols + w - 1) // w
    return {f"{r},{c}": (r // h) * per + (c // w) for r in range(rows) for c in range(cols)}


# ---------------------------------------------------------------------------
# nothree — No Three
# ---------------------------------------------------------------------------
NOTHREE_INST = {
    "puzzle": "nothree",
    "rows": 6,
    "cols": 6,
    "clues": {
        "o": {
            "1,0": 1, "0,3": 1, "5,4": 1, "5,0": 1, "2,5": 1, "4,5": 1,
        },
    },
}
NOTHREE_GRID = G("""
. # . . . .
. . . . # .
. . . . . .
. . . . . .
# . . . # .
. . . . . .
""")

# ---------------------------------------------------------------------------
# sumiwake — Sumiwake
# ---------------------------------------------------------------------------
SUMIWAKE_INST = {
    "puzzle": "sumiwake",
    "rows": 6,
    "cols": 6,
    "clues": {
        "o": {
            "2,2": 2,  # black circle: exactly two black 8-neighbours
            "0,1": 1, "0,0": 1, "3,3": 1, "0,3": 1, "2,4": 1,
        },
    },
    "regions": _block_regions(6, 6),
}
SUMIWAKE_GRID = G("""
. # . . . .
. . # . . .
. . . . # .
# . . # . .
. # . . . #
. . . # . .
""")

# ---------------------------------------------------------------------------
# usoone — Uso-One (clues derived from a hand-verified ring of blacks)
# ---------------------------------------------------------------------------
USOONE_INST = {
    "puzzle": "usoone",
    "rows": 6,
    "cols": 6,
    "clues": {
        "n": {
            "0,0": 0, "0,1": 3, "0,2": 0, "0,3": 2, "0,4": 1, "0,5": 2,
            "2,0": 0, "2,1": 4, "2,2": 0, "2,3": 2, "2,4": 2, "2,5": 2,
            "4,0": 0, "4,1": 4, "4,2": 0, "4,3": 2, "4,4": 2, "4,5": 2,
        },
    },
    "regions": _block_regions(6, 6),
}
USOONE_GRID = G("""
. . . . . .
. . . . # .
. . . . . .
. . . . # .
. . . . . .
. . . . # .
""")

# ---------------------------------------------------------------------------
# yajikazu — Yajisan-Kazusan
# ---------------------------------------------------------------------------
YAJIKAZU_INST = {
    "puzzle": "yajikazu",
    "rows": 6,
    "cols": 6,
    "clues": {
        "d": {
            "2,0": 3, "0,2": 1, "4,1": 3, "2,4": 1, "0,4": 1, "2,5": 0,
            "5,0": 3, "3,2": 0, "2,3": 0, "2,2": 3,
        },
        "n": {
            "2,0": 1, "0,2": 1, "4,1": 1, "2,4": 0, "0,4": 0, "2,5": 0,
            "5,0": 0, "3,2": 1, "2,3": 0, "2,2": 9,  # arrow on a black cell: ignored
        },
    },
}
YAJIKAZU_GRID = G("""
# . . . . .
. . . . . .
. . # . . .
. . . . . .
. # . . . .
. . . . . .
""")

# ---------------------------------------------------------------------------
# ayeheya — Ayeheya
# ---------------------------------------------------------------------------
AYEHEYA_INST = {
    "puzzle": "ayeheya",
    "rows": 6,
    "cols": 6,
    "clues": {
        "n": {
            "0,0": 0, "0,2": 2, "0,4": 0, "2,0": 2, "2,2": 0, "2,4": 2,
            "4,0": 0, "4,2": 2, "4,4": 0,
        },
    },
    "regions": _block_regions(6, 6),
}
AYEHEYA_GRID = G("""
. . . # . .
. . # . . .
# . . . # .
. # . . . #
. . . # . .
. . # . . .
""")

# ---------------------------------------------------------------------------
# bosnianroad — Bosnian Road
# ---------------------------------------------------------------------------
BOSNIANROAD_INST = {
    "puzzle": "bosnianroad",
    "rows": 6,
    "cols": 6,
    "clues": {
        "n": {
            "0,0": 1, "0,2": 3, "2,2": 5, "2,3": 5, "5,2": 3, "5,4": 2,
            "0,4": 2, "1,0": 2, "4,0": 2, "3,2": 5, "5,0": 1, "0,5": 1,
            "2,0": 3, "5,5": 1,
        },
    },
}
BOSNIANROAD_GRID = G("""
. . . . . .
. # # # # .
. # . . # .
. # . . # .
. # # # # .
. . . . . .
""")

# ---------------------------------------------------------------------------
# sansaroad — Sansa Road
# ---------------------------------------------------------------------------
SANSAROAD_INST = {
    "puzzle": "sansaroad",
    "rows": 6,
    "cols": 6,
    "clues": {
        "t": {
            "1,1": 1, "2,1": 3, "3,1": 3, "1,3": 3, "2,3": 2, "3,3": 2,
            "4,1": 1, "1,4": 3, "0,4": 1,
        },
        "v": {"0,2": 1, "5,2": 1},  # the two degree-3 junctions
    },
}
SANSAROAD_GRID = G("""
. . . . . .
. # . # # .
. # . # # .
. # . # # .
. # . # # .
. . . . . .
""")

# ---------------------------------------------------------------------------
# dominion — Dominion
# ---------------------------------------------------------------------------
DOMINION_INST = {
    "puzzle": "dominion",
    "rows": 6,
    "cols": 6,
    "clues": {
        "a": {"0,2": 1, "1,1": 1, "3,3": 1, "5,4": 1},
    },
}
DOMINION_GRID = G("""
. . . . . .
. . # . . .
. . # . . .
. . . . # .
. . . . # .
. . . . . .
""")

# ---------------------------------------------------------------------------
# norinuri — Norinuri
# ---------------------------------------------------------------------------
NORINURI_INST = {
    "puzzle": "norinuri",
    "rows": 6,
    "cols": 6,
    "clues": {"n": {"0,2": 30}},
}
NORINURI_GRID = G("""
. . . . . .
. # # . . #
. . . . . #
. . . . . .
. . . . . .
. . . . # #
""")

# ---------------------------------------------------------------------------
# isowatari — Isowatari (n=2)
# ---------------------------------------------------------------------------
ISOWATARI_INST = {
    "puzzle": "isowatari",
    "rows": 6,
    "cols": 6,
    "clues": {
        "o": {"0,0": 2, "1,1": 1, "3,3": 1, "5,0": 1},
    },
    "params": {"n": 2},
}
ISOWATARI_GRID = G("""
# . . # # .
# . # . . .
. . # . # #
# . . . . .
# . # . # .
. . # . # .
""")

# ---------------------------------------------------------------------------
# aquarium — Aquarium
# ---------------------------------------------------------------------------
AQUARIUM_INST = {
    "puzzle": "aquarium",
    "rows": 6,
    "cols": 6,
    "clues": {},
    "regions": _block_regions(6, 6),
    "params": {
        "left": [2, 4, 0, 4, 4, 4],
        "top": [3, 3, 3, 3, 3, 3],
    },
}
AQUARIUM_GRID = G("""
. . # # . .
. . # # # #
. . . . . .
# # # # . .
# # . . # #
# # . . # #
""")

# ---------------------------------------------------------------------------

CASES = [
    ("nothree", NOTHREE_INST, NOTHREE_GRID,
     "isolated blacks + equal-spacing ban, 6 circles pinning the ring"),
    ("sumiwake", SUMIWAKE_INST, SUMIWAKE_GRID,
     "2x2 regions, white & black circles, diagonal lattice with runs in <=2 regions"),
    ("usoone", USOONE_INST, USOONE_GRID,
     "one wrong clue per 2x2 region, 18 clues, blacks in a column ring"),
    ("yajikazu", YAJIKAZU_INST, YAJIKAZU_GRID,
     "arrow ray-counting, including an arrow placed on a black cell (ignored)"),
    ("ayeheya", AYEHEYA_INST, AYEHEYA_GRID,
     "per-region 180deg symmetry + region black counts on a diagonal lattice"),
    ("bosnianroad", BOSNIANROAD_INST, BOSNIANROAD_GRID,
     "a rectangular ring (12 black cells) with 14 number clues"),
    ("sansaroad", SANSAROAD_INST, SANSAROAD_GRID,
     "border ring + one chord, two degree-3 junctions, 9 dot clues"),
    ("dominion", DOMINION_INST, DOMINION_GRID,
     "non-touching 1x2 dominoes, letters all in one white region"),
    ("norinuri", NORINURI_INST, NORINURI_GRID,
     "dominoes, single white region sized by the one number"),
    ("isowatari", ISOWATARI_INST, ISOWATARI_GRID,
     "six dominoes (n=2) tiled so every 2x2 window has a black"),
    ("aquarium", AQUARIUM_INST, AQUARIUM_GRID,
     "nine 2x2 regions with water levels + full row/col counts"),
]
